export const tagsCatalog = [
  {
    title: 'Localidade',
    tags: [
      'Aguada',
      'Barra dos Coqueiros',
      'Estância',
      'Lagarto',
      'Laranjeiras',
      'São Cristóvão',
    ],
  },
  {
    title: 'Manifestação cultural',
    tags: [
      'Bacamarte',
      'Batalhão',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Divina Pastora',
      'Festas juninas',
      'Gerais',
      'Guerreiro',
      'Lambe-sujo',
      'Maracatu',
      'Nagô',
      'Parafusos',
      'Pífanos',
      'Quilombos',
      'Reisado',
      'Renda Irlandesa',
      'Samba',
      'São Gonçalo',
      'Taieiras',
      'Zabumba',
    ],
  },
  {
    title: 'Escolaridade',
    tags: [
      'Educação Infantil',
      'Ensino Fundamental',
      'Ensino Fundamental II',
      'Ensino Médio',
    ],
  },
  {
    title: 'Assuntos correlatos',
    tags: [
      'Abolição',
      'Afro sergipano',
      'Apresentação',
      'Boi',
      'Brejão dos Negros',
      'Capitalismo',
      'Conflitos Mundiais',
      'Couro',
      'Cultura',
      'Dança',
      'Debate',
      'Diáspora',
      'Escravidão',
      'Festejos natalinos',
      'Festa das Cabacinhas',
      'Formação histórica',
      'Formas de organização social',
      'Fotografia',
      'Identidade',
      'Imagem',
      'Instrumentos Musicais',
      'Interpretação de texto',
      'Irmandades',
      'Japaratuba',
      'Legislação',
      'Lenda',
      'Liberdade',
      'Linguagens',
      'Maloca',
      'Manifestação Cultural',
      'Manifestações culturais',
      'Máscara',
      'Mestre Deca',
      'Mestre Rindú',
      'Mosqueiro',
      'Música',
      'Musicalidade',
      'Patrimônio Cultural',
      'Patrimônio Histórico',
      'Patrimônio Imaterial',
      'Pecuária',
      'Percepção Musical',
      'Pintura',
      'Porto D’Areia',
      'Porto da Folha',
      'Provérbios',
      'Pulsação/ Parlendas',
      'Quilombo',
      'Quilombo Urbano',
      'Quilombo Mocambo',
      'Racismo',
      'Redes Sociais',
      'Religiosidade',
      'Resistência',
      'Rima',
      'Semiótica',
      'Símbolos',
      'Sincretismo',
      'Socialismo',
      'Teatro',
    ],
  },
  {
    title: 'Disciplina',
    tags: [
      'Artes',
      'Dança',
      'Educação física',
      'Geografia',
      'História',
      'Literatura',
      'Matemática',
      'Música',
      'Português',
      'Redação',
      'Teatro',
    ],
  },
  {
    title: 'Momento histórico',
    tags: [
      'Brasil Colônia',
      'Brasil Império',
      'Brasil República',
      'Império',
      'Pós-abolição',
      'Revolução Russa',
      'Século XIX',
    ],
  },
  {
    title: 'Tipo de atividade',
    tags: [
      'Caça-palavras',
      'História em Quadrinhos',
      'Jogo',
      'Jogo da memória',
      'Texto',
      'Trabalho',
      'Trabalho manual',
      'Plano de Aula',
      'Poema',
      'Questões',
      'Quiz',
      'Roteiro histórico-cultural',
    ],
  },
]
