export const tagsCatalog = [
  {
    title: 'Localidade',
    tags: [
      'Aguada',
      'Barra dos Coqueiros',
      'Lagarto',
      'Laranjeiras',
      'São Cristóvão',
    ],
  },
  {
    title: 'Manifestação cultural',
    tags: [
      'Bacamarte',
      'Batalhão',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Divina Pastora',
      'Festas juninas',
      'Gerais',
      'Guerreiro',
      'Lambe-sujo',
      'Maracatu',
      'Nagô',
      'Parafusos',
      'Pífanos',
      'Quilombos',
      'Reisado',
      'Renda Irlandesa',
      'Samba',
      'São Gonçalo',
      'Taieiras',
      'Zabumba',
    ],
  },
  {
    title: 'Escolaridade',
    tags: ['Educação Infantil', 'Ensino Fundamental', 'Ensino Médio'],
  },
  {
    title: 'Assuntos correlatos',
    tags: [
      'Abolição',
      'Afro sergipano',
      'Boi',
      'Capitalismo',
      'Conflitos Mundiais',
      'Couro',
      'Cultura',
      'Dança',
      'Diáspora',
      'Escravidão',
      'Festejos natalinos',
      'Formação histórica',
      'Formas de organização social',
      'Fotografia',
      'Identidade',
      'Instrumentos musicais',
      'Interpretação de texto',
      'Irmandades',
      'Legislação',
      'Lenda',
      'Liberdade',
      'Linguagens',
      'Maloca',
      'Manifestação Cultural',
      'Manifestações culturais',
      'Máscara',
      'Mestre Deca',
      'Mestre Rindú',
      'Mosqueiro',
      'Música',
      'Musicalidade',
      'Patrimônio Cultural',
      'Patrimônio Histórico',
      'Patrimônio Imaterial',
      'Pecuária',
      'Quilombo',
      'Racismo',
      'Redes Sociais',
      'Religiosidade',
      'Resistência',
      'Rima',
      'Semiótica',
      'Símbolos',
      'Sincretismo',
      'Socialismo',
      'Teatro',
    ],
  },
  {
    title: 'Disciplina',
    tags: [
      'Artes',
      'Dança',
      'Educação física',
      'Geografia',
      'História',
      'Literatura',
      'Matemática',
      'Música',
      'Português',
      'Redação',
      'Teatro',
    ],
  },
  {
    title: 'Momento histórico',
    tags: [
      'Brasil Colônia',
      'Brasil Império',
      'Brasil República',
      'Império',
      'Pós-abolição',
      'Revolução Russa',
      'Século XIX',
    ],
  },
  {
    title: 'Tipo de atividade',
    tags: [
      'Caça-palavras',
      'Jogo',
      'Jogo da memória',
      'Texto',
      'Trabalho',
      'Trabalho manual',
    ],
  },
]
