export const citysCard = [
  {
    nome: 'Amparo do São Francisco',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Aquidabã',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Aracaju',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Arauá',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Barra dos Coqueiros',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Brejo Grande',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Canoa',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Canhoba',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Canidé de São Francisco',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Capela',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Carira',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Carmópolis',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Cedro de São João',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Cristinápolis',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Divina Pastora',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Gararu',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'General Maynard',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Graccho Cardoso',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Ilha das Flores',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Itabaiana',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Itaporanga',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Japatatuba',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Lagarto',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Laranjeiras',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Macambira',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Malhador',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Moita Bonita',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Monte Alegre',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Mussuca- Laranjeiras',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Neópolis',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Pacatuba',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Pedrinhas',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Pirambu',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Propriá',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Riachuelo',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Rosário do Catete',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Santana de São Francisco',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Santo Amaro',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Santo Amaro das Brotas',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'São Cristóvão',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'São Domingos',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'São Miguel do Aleixo',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Simão Dias',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
  {
    nome: 'Tobias Barreto',
    manifestacoes: [
      'Barco de fogo',
      'Batalhão',
      'Batucada',
      'Caceteira',
      'Cacumbi',
      'Capoeira',
      'Chegança',
      'Guerreiro',
    ],
  },
]
