export const manifestationsCard = [
  {
    nome: 'Barco de fogo',
    cidades: [
      'Amparo do São Francisco',
      'Aquidabã',
      'Aracaju',
      'Arauá',
      'Barra dos Coqueiros',
      'Brejo Grande',
      'Canoa',
      'Canhoba',
      'Canidé de São Francisco',
      'Capela',
    ],
  },
  {
    nome: 'Batalhão',
    cidades: [
      'Amparo do São Francisco',
      'Aquidabã',
      'Aracaju',
      'Arauá',
      'Barra dos Coqueiros',
      'Brejo Grande',
      'Canoa',
      'Canhoba',
      'Canidé de São Francisco',
      'Capela',
    ],
  },
  {
    nome: 'Batucada',
    cidades: [
      'Amparo do São Francisco',
      'Aquidabã',
      'Aracaju',
      'Arauá',
      'Barra dos Coqueiros',
      'Brejo Grande',
      'Canoa',
      'Canhoba',
      'Canidé de São Francisco',
      'Capela',
    ],
  },
  {
    nome: 'Caceteira',
    cidades: [
      'Amparo do São Francisco',
      'Aquidabã',
      'Aracaju',
      'Arauá',
      'Barra dos Coqueiros',
      'Brejo Grande',
      'Canoa',
      'Canhoba',
      'Canidé de São Francisco',
      'Capela',
    ],
  },
  {
    nome: 'Cacumbi',
    cidades: [
      'Amparo do São Francisco',
      'Aquidabã',
      'Aracaju',
      'Arauá',
      'Barra dos Coqueiros',
      'Brejo Grande',
      'Canoa',
      'Canhoba',
      'Canidé de São Francisco',
      'Capela',
    ],
  },
  {
    nome: 'Capoeira',
    cidades: [
      'Amparo do São Francisco',
      'Aquidabã',
      'Aracaju',
      'Arauá',
      'Barra dos Coqueiros',
      'Brejo Grande',
      'Canoa',
      'Canhoba',
      'Canidé de São Francisco',
      'Capela',
    ],
  },
  {
    nome: 'Chegança',
    cidades: [
      'Amparo do São Francisco',
      'Aquidabã',
      'Aracaju',
      'Arauá',
      'Barra dos Coqueiros',
      'Brejo Grande',
      'Canoa',
      'Canhoba',
      'Canidé de São Francisco',
      'Capela',
    ],
  },
  {
    nome: 'Guerreiro',
    cidades: [
      'Amparo do São Francisco',
      'Aquidabã',
      'Aracaju',
      'Arauá',
      'Barra dos Coqueiros',
      'Brejo Grande',
      'Canoa',
      'Canhoba',
      'Canidé de São Francisco',
      'Capela',
    ],
  },
  {
    nome: 'Lambe-sujo',
    cidades: [
      'Amparo do São Francisco',
      'Aquidabã',
      'Aracaju',
      'Arauá',
      'Barra dos Coqueiros',
      'Brejo Grande',
      'Canoa',
      'Canhoba',
      'Canidé de São Francisco',
      'Capela',
    ],
  },
  {
    nome: 'Maracatu',
    cidades: [
      'Amparo do São Francisco',
      'Aquidabã',
      'Aracaju',
      'Arauá',
      'Barra dos Coqueiros',
      'Brejo Grande',
      'Canoa',
      'Canhoba',
      'Canidé de São Francisco',
      'Capela',
    ],
  },
  {
    nome: 'Nagô',
    cidades: [
      'Amparo do São Francisco',
      'Aquidabã',
      'Aracaju',
      'Arauá',
      'Barra dos Coqueiros',
      'Brejo Grande',
      'Canoa',
      'Canhoba',
      'Canidé de São Francisco',
      'Capela',
    ],
  },
  {
    nome: 'Parafusos',
    cidades: [
      'Amparo do São Francisco',
      'Aquidabã',
      'Aracaju',
      'Arauá',
      'Barra dos Coqueiros',
      'Brejo Grande',
      'Canoa',
      'Canhoba',
      'Canidé de São Francisco',
      'Capela',
    ],
  },
  {
    nome: 'Pífano',
    cidades: [
      'Amparo do São Francisco',
      'Aquidabã',
      'Aracaju',
      'Arauá',
      'Barra dos Coqueiros',
      'Brejo Grande',
      'Canoa',
      'Canhoba',
      'Canidé de São Francisco',
      'Capela',
    ],
  },
  {
    nome: 'Reisado',
    cidades: [
      'Amparo do São Francisco',
      'Aquidabã',
      'Aracaju',
      'Arauá',
      'Barra dos Coqueiros',
      'Brejo Grande',
      'Canoa',
      'Canhoba',
      'Canidé de São Francisco',
      'Capela',
    ],
  },
  {
    nome: 'Renda irlandesa',
    cidades: [
      'Amparo do São Francisco',
      'Aquidabã',
      'Aracaju',
      'Arauá',
      'Barra dos Coqueiros',
      'Brejo Grande',
      'Canoa',
      'Canhoba',
      'Canidé de São Francisco',
      'Capela',
    ],
  },
  {
    nome: 'Samba de aboio',
    cidades: [
      'Amparo do São Francisco',
      'Aquidabã',
      'Aracaju',
      'Arauá',
      'Barra dos Coqueiros',
      'Brejo Grande',
      'Canoa',
      'Canhoba',
      'Canidé de São Francisco',
      'Capela',
    ],
  },
  {
    nome: 'Samba de coco',
    cidades: [
      'Amparo do São Francisco',
      'Aquidabã',
      'Aracaju',
      'Arauá',
      'Barra dos Coqueiros',
      'Brejo Grande',
      'Canoa',
      'Canhoba',
      'Canidé de São Francisco',
      'Capela',
    ],
  },
  {
    nome: 'Samba de pareia',
    cidades: [
      'Amparo do São Francisco',
      'Aquidabã',
      'Aracaju',
      'Arauá',
      'Barra dos Coqueiros',
      'Brejo Grande',
      'Canoa',
      'Canhoba',
      'Canidé de São Francisco',
      'Capela',
    ],
  },
  {
    nome: 'São Gonçalo',
    cidades: [
      'Amparo do São Francisco',
      'Aquidabã',
      'Aracaju',
      'Arauá',
      'Barra dos Coqueiros',
      'Brejo Grande',
      'Canoa',
      'Canhoba',
      'Canidé de São Francisco',
      'Capela',
    ],
  },
  {
    nome: 'Taieiras',
    cidades: [
      'Amparo do São Francisco',
      'Aquidabã',
      'Aracaju',
      'Arauá',
      'Barra dos Coqueiros',
      'Brejo Grande',
      'Canoa',
      'Canhoba',
      'Canidé de São Francisco',
      'Capela',
    ],
  },
]
