export const cidades = [
  'Amparo do São Francisco',
  'Aquidabã',
  'Aracaju',
  'Barra dos Coqueiros',
  'Brejo Grande',
  'Canhoba',
  'Canidé de São Francisco',
  'Capela',
  'Carira',
  'Carmópolis',
  'Cedro de São João',
  'Cristinápolis',
  'Divina Pastora',
  'Estância',
  'Gararu',
  'General Maynard',
  'Graccho Cardoso',
  'Ilha das Flores',
  'Itabaiana',
  'Itaporanga',
  'Japaratuba',
  'Lagarto',
  'Laranjeiras',
  'Macambira',
  'Moita Bonita',
  'Neópolis',
  'Pacatuba',
  'Pedrinhas',
  'Pirambu',
  'Propriá',
  'Riachuelo',
  'Rosário do Catete',
  'Santana de São Francisco',
  'Santo Amaro das Brotas',
  'São Cristóvão',
  'São Domingos',
  'Simão Dias',
  'Tobias Barreto',
]

export const manifestacoes = [
  'Barco de fogo',
  'Batalhão',
  'Batucada',
  'Caceteira',
  'Cacumbi',
  'Capoeira',
  'Chegança',
  'Guerreiro',
  'Lambe-sujo',
  'Maracatu',
  'Nagô',
  'Parafusos',
  'Pífano',
  'Reisado',
  'Renda irlandesa',
  'Samba de aboio',
  'Samba de coco',
  'Samba de pareia',
  'São Gonçalo',
  'Taieiras',
]
