export const cidades = [
  'Amparo do São Francisco',
  'Aquidabã',
  'Aracaju',
  'Barra dos Coqueiros',
  'Brejo Grande',
  'Capela',
  'Carira',
  'Carmópolis',
  'Cristinápolis',
  'Divina Pastora',
  'Estância',
  'Gararu',
  'General Maynard',
  'Graccho Cardoso',
  'Itabaiana',
  'Itaporanga',
  'Japaratuba',
  'Lagarto',
  'Laranjeiras',
  'Macambira',
  'Moita Bonita',
  'Pacatuba',
  'Pedrinhas',
  'Riachuelo',
  'Rosário do Catete',
  'Santo Amaro das Brotas',
  'São Cristóvão',
  'São Domingos',
  'Tobias Barreto',
]

export const manifestacoes = [
  'Barco de fogo',
  'Batalhão',
  'Batucada',
  'Caceteira',
  'Cacumbi',
  'Capoeira',
  'Chegança',
  'Guerreiro',
  'Lambe-sujo',
  'Maracatu',
  'Nagô',
  'Parafusos',
  'Pífano',
  'Reisado',
  'Renda irlandesa',
  'Samba de aboio',
  'Samba de coco',
  'Samba de pareia',
  'São Gonçalo',
  'Taieiras',
]
