export const cidades = [
  'Amparo do São Francisco',
  'Aquidabã',
  'Aracaju',
  'Arauá',
  'Barra dos Coqueiros',
  'Brejo Grande',
  'Canoa',
  'Canhoba',
  'Canidé de São Francisco',
  'Capela',
  'Carira',
  'Carmópolis',
  'Cedro de São João',
  'Cristinápolis',
  'Divina Pastora',
  'Gararu',
  'General Maynard',
  'Graccho Cardoso',
  'Ilha das Flores',
  'Itabaiana',
  'Itaporanga',
  'Japatatuba',
  'Lagarto',
  'Laranjeiras',
  'Macambira',
  'Malhador',
  'Moita Bonita',
  'Monte Alegre',
  'Mussuca- Laranjeiras',
  'Neópolis',
  'Pacatuba',
  'Pedrinhas',
  'Pirambu',
  'Propriá',
  'Riachuelo',
  'Rosário do Catete',
  'Santana de São Francisco',
  'Santo Amaro',
  'Santo Amaro das Brotas',
  'São Cristóvão',
  'São Domingos',
  'São Miguel do Aleixo',
  'Simão Dias',
  'Tobias Barreto',
]

export const manifestacoes = [
  'Bacamarteiros',
  'Barco de fogo',
  'Batalhão',
  'Batucada',
  'Caceteira',
  'Cacumbi',
  'Capoeira',
  'Chegança',
  'Guerreiro',
  'Lambe-sujo',
  'Literatura',
  'Maracatu',
  'Nagô',
  'Parafusos',
  'Pífano',
  'Reisado',
  'Renda irlandesa',
  'Samba de aboio',
  'Samba de coco',
  'Samba de pareia',
  'São Gonçalo',
  'Taieiras',
]
